# Çeşitli Dosya Tiplerini indirme ve kaydetme

# 1.csv dosyaları

In [10]:
import pandas as pd

In [13]:
d =pd.read_csv("https://data.cdc.gov/api/views/bi63-dtpu/rows.csv")
d

,Year,113 Cause Name,Cause Name,State,Deaths,Age-adjusted Death Rate
0,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Alabama,2313.0,52.2
1,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Alaska,294.0,55.9
2,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Arizona,2214.0,44.8
3,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Arkansas,1287.0,47.6
4,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,California,9198.0,28.7
5,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Colorado,1519.0,39.0
6,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Connecticut,1034.0,29.3
7,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Delaware,267.0,35.3
8,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,District of Columbia,161.0,28.4
9,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Florida,5961.0,35.7
10,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Georgia,3078.0,41.5
11,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Hawaii,293.0,24.3
12,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Idaho,597.0,48.3
13,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Illinois,4125.0,33.7
14,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Indiana,2309.0,38.4
15,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Iowa,1123.0,35.2
16,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Kansas,1126.0,40.7
17,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Kentucky,1730.0,43.3
18,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Louisiana,1940.0,44.7
19,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Maine,458.0,34.9
20,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Maryland,1296.0,25.9
21,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Massachusetts,1303.0,19.6
22,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Michigan,3188.0,32.8
23,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Minnesota,1772.0,35.8
24,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Mississippi,1642.0,58.9
25,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Missouri,2465.0,43.2
26,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Montana,461.0,50.3
27,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Nebraska,668.0,37.3
28,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,Nevada,710.0,38.5
29,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional Injuries,New Hampshire,329.0,27.5
...,...,...,...,...,...,...
14998,2015,Septicemia (A40-A41),Septicemia,Michigan,1268.0,10.3
14999,2015,Septicemia (A40-A41),Septicemia,Minnesota,439.0,6.6
15000,2015,Septicemia (A40-A41),Septicemia,Mississippi,676.0,20.2
15001,2015,Septicemia (A40-A41),Septicemia,Missouri,856.0,11.6
15002,2015,Septicemia (A40-A41),Septicemia,Montana,112.0,8.7
15003,2015,Septicemia (A40-A41),Septicemia,Nebraska,158.0,7.0
15004,2015,Septicemia (A40-A41),Septicemia,Nevada,205.0,6.7
15005,2015,Septicemia (A40-A41),Septicemia,New Hampshire,119.0,7.0
15006,2015,Septicemia (A40-A41),Septicemia,New Jersey,1957.0,17.9
15007,2015,Septicemia (A40-A41),Septicemia,New Mexico,232.0,9.6
15008,2015,Septicemia (A40-A41),Septicemia,New York,2601.0,10.9
15009,2015,Septicemia (A40-A41),Septicemia,North Carolina,1557.0,13.6
15010,2015,Septicemia (A40-A41),Septicemia,North Dakota,81.0,9.4
15011,2015,Septicemia (A40-A41),Septicemia,Ohio,1957.0,13.6
15012,2015,Septicemia (A40-A41),Septicemia,Oklahoma,419.0,9.5
15013,2015,Septicemia (A40-A41),Septicemia,Oregon,227.0,4.6
15014,2015,Septicemia (A40-A41),Septicemia,Pennsylvania,2343.0,13.5
15015,2015,Septicemia (A40-A41),Septicemia,Rhode Island,143.0,10.4
15016,2015,Septicemia (A40-A41),Septicemia,South Carolina,854.0,14.9
15017,2015,Septicemia (A40-A41),Septicemia,South Dakota,120.0,11.1
15018,2015,Septicemia (A40-A41),Septicemia,Tennessee,924.0,12.1
15019,2015,Septicemia (A40-A41),Septicemia,Texas,4381.0,17.2
15020,2015,Septicemia (A40-A41),Septicemia,United States,40773.0,11.0
15021,2015,Septicemia (A40-A41),Septicemia,Utah,166.0,7.0
15022,2015,Septicemia (A40-A41),Septicemia,Vermont,50.0,5.9
15023,2015,Septicemia (A40-A41),Septicemia,Virginia,1187.0,13.0
15024,2015,Septicemia (A40-A41),Septicemia,Washington,501.0,6.3
15025,2015,Septicemia (A40-A41),Septicemia,West Virginia,348.0,13.9
15026,2015,Septicemia (A40-A41),Septicemia,Wisconsin,517.0,7.2
15027,2015,Septicemia (A40-A41),Septicemia,Wyoming,46.0,7.1

In [15]:
d["State"].tolist()

['Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Colorado',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Vermont',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'Texas',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Nevada',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Missouri',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Montana',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'Maine',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Kansas',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'United States',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 ...]

In [17]:
state=d["State"].to_frame()

In [20]:
state.to_csv("state.csv",index=False)

In [21]:
pd.read_csv("state.csv")

                      State
0                   Alabama
1                    Alaska
2                   Arizona
3                  Arkansas
4                California
5                  Colorado
6               Connecticut
7                  Delaware
8      District of Columbia
9                   Florida
10                  Georgia
11                   Hawaii
12                    Idaho
13                 Illinois
14                  Indiana
15                     Iowa
16                   Kansas
17                 Kentucky
18                Louisiana
19                    Maine
20                 Maryland
21            Massachusetts
22                 Michigan
23                Minnesota
24              Mississippi
25                 Missouri
26                  Montana
27                 Nebraska
28                   Nevada
29            New Hampshire
...                     ...
14998              Michigan
14999             Minnesota
15000           Mississippi
15001              Missouri
15002               Montana
15003              Nebraska
15004                Nevada
15005         New Hampshire
15006            New Jersey
15007            New Mexico
15008              New York
15009        North Carolina
15010          North Dakota
15011                  Ohio
15012              Oklahoma
15013                Oregon
15014          Pennsylvania
15015          Rhode Island
15016        South Carolina
15017          South Dakota
15018             Tennessee
15019                 Texas
15020         United States
15021                  Utah
15022               Vermont
15023              Virginia
15024            Washington
15025         West Virginia
15026             Wisconsin
15027               Wyoming

[15028 rows x 1 columns]

# 2.excel dosyaları

In [24]:
c = pd.read_excel("excel.xlsx",sheet_name=["2006","2010"])

In [26]:
c["2010"]

          Futbolcu  Gol
0      David Villa    5
1  Wesley Sneijder    5
2     Diego Forlan    5
3    Thomas Müller    5
4   Miroslav Klose    4
5    Robert Vittek    4
6        G.Higuain    4
7     Asamoah Gyan    3
8   Landon Donovan    3
9      Luis Suares    3

In [29]:
dört=pd.read_csv("2014 wc.csv")

In [30]:
dört.to_excel("2014.xlsx",sheet_name="2014")

# 3.html dosyaları

In [32]:
b=pd.read_html("https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/List_of_banks_in_Turkey.html")

In [33]:
b[0]

,0,1,2,3
0,Bank,Foundation,# of branches As of 22 February 2016,Total assets (million TL) As of September 2015[4]
1,Ziraat Bankası,1863,1789,299084
2,Türkiye İş Bankası,1924,1355,279942
3,Garanti Bank,1946,974,260700
4,Akbank,1948,901,236148
5,Yapı ve Kredi Bankası,1944,997,232248
6,Halk Bankası,1938,948,189686
7,VakıfBank,1954,917,188820
8,Finansbank,1987,641,90410
9,Türk Ekonomi Bankası,1927,528,73666
10,Denizbank,1997,691,82195
11,HSBC Bank,1990,280,32869
12,ING Bank,1984,288,51645
13,Türk Eximbank,1987,3,46518
14,Odeabank,2012,55,32841
15,Şekerbank,1953,300,23777
16,İller Bankası,1933,19,17494
17,Türkiye Sınai Kalkınma Bankası,1950,3,20853
18,Alternatif Bank,1992,57,13793
19,Citibank,1980,8,8920
20,Anadolubank,1996,106,11620
21,Burgan Bank,1992,55,10696
22,İstanbul Takas ve Saklama Bankası,1995,1,7631
23,Tekstilbank,1986,44,6264
24,Deutsche Bank,1988,1,2681
25,Fibabanka,1984,68,9476
26,Aktif Yatırım Bankası,1999,8,7383
27,The Royal Bank of Scotland,1921,1,1754
28,Türkiye Kalkınma Bankası,1975,1,4975
29,Turkland Bank,1991,34,5651
30,Bank of Tokyo-Mitsubishi UFJ Turkey,2013,1,4737
31,Arap Türk Bankası,1977,7,3975
32,Intesa Sanpaolo S.p.A.,2013,1,3925
33,Merrill Lynch,1992,1,204
34,BankPozitif,1999,1,2090
35,Société Générale,1989,1,477
36,Turkish Bank,1982,13,1397
37,Rabobank,2014,1,843
38,JPMorgan Chase,1984,1,392
39,Birleşik Fon Bankası,1958,1,2450
40,Bank Mellat,1982,3,354
41,Nurol Yatırım Bankası,1999,1,788
42,Diler Yatırım Bankası,1998,1,116
43,GSD Yatırım Bankası,1998,1,231
44,Habib Bank Limited,1983,1,113
45,Credit Agricole (Standard Chartered),1990,1,83
46,Adabank,1985,1,53
47,Taib Yatırım Bank (Pasha Yatırım),1987,1,276